### ISSUE TITLE
Internal error occuring when using the action

### ISSUE THREAD

**Issue by mishioo** [kalgurn/update-project-item-status#218]
Hello,

I tried to use the action in my organization's project (not classic) to update PR's status on the board, but got the following error:

```
Error: Request failed due to the following response errors:
 - Field 'projectNext' doesn't exist on type 'Organization'
 - Variable $projectNumber is declared by getProject but not used
```

Any thoughts on what might be the cause of this behaviour? Help appreciated!

The workflow I used:
```
name: Add PR to In Review column
on:
  pull_request:
    types: [opened]

jobs:
  pr_created:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/orgs/my_organization/projects/1
          github-token: ${{ secrets.GHPROJECT_TOKEN }}

      - uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/orgs/my_organization/projects/1
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          status: "In Review"
```
