### ISSUE TITLE
Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by Klaitos** [kalgurn/update-project-item-status#90]
Hello,

I have issue with your action when running it.

```
      - uses: actions/add-to-project@v0.3.0
        id: addItem
        with:
          project-url: https://github.com/orgs/myorg/projects/myid
          github-token: ${{ secrets.PAT }}
      - uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/orgs/myorg/projects/myid
          github-token: ${{ secrets.PAT }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          status: "In Progress"
```

Error thrown : 

```
Run kalgurn/update-project-item-status@main
  with:
    project-url: https://github.com/orgs/myorg/projects/myid
    github-token: ***
    item-id: XXXXXX
    status: In Progress
Error: Cannot read properties of null (reading 'id')
```
